#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022-present JELOS (https://github.com/JustEnoughLinuxOS)

# Adapt retroarch joypad config for rgb10

if [ ! -f "/storage/joypads/Twin USB Joystick.cfg" ]; then
    tee /storage/joypads/Twin\ USB\ Joystick.cfg <<EOF
input_driver = "udev"
input_device = "Twin USB Joystick"
input_vendor_id = "8380"
input_product_id = "21760"
input_b_btn = "0"
input_y_btn = "4"
input_select_btn = "10"
input_start_btn = "11"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "1"
input_x_btn = "3"
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "8"
input_r2_btn = "9"
input_l3_btn = "13"
input_r3_btn = "14"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+2"
input_r_y_minus_axis = "-2"
EOF
fi

if [ ! -f "/storage/joypads/ShanWan PC_PS3_Android.cfg" ]; then
    tee /storage/joypads/ShanWan\ PC_PS3_Android.cfg <<EOF
input_driver = "udev"
input_device = "ShanWan PC/PS3/Android"
input_vendor_id = "8380"
input_product_id = "21760"
input_b_btn = "0"
input_y_btn = "4"
input_select_btn = "10"
input_start_btn = "11"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "1"
input_x_btn = "3"
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "8"
input_r2_btn = "9"
input_l3_btn = "13"
input_r3_btn = "14"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+2"
input_r_y_minus_axis = "-2"
EOF
fi

if [ ! -f "/storage/joypads/Twin USB Joystick Twin USB Joystick.cfg" ]; then
    tee /storage/joypads/Twin\ USB\ Joystick\ Twin\ USB\ Joystick.cfg <<EOF
input_driver = "udev"
input_device = "Twin USB Joystick Twin USB Joystick"
input_vendor_id = "8380"
input_product_id = "21760"
input_b_btn = "0"
input_y_btn = "3"
input_select_btn = "10"
input_start_btn = "11"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "1"
input_x_btn = "4"
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "8"
input_r2_btn = "9"
input_l3_btn = "13"
input_r3_btn = "14"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+2"
input_r_y_minus_axis = "-2"
EOF
fi

if [ -e "/tmp/joypads/retrogame_joypad.cfg" ]; then
    sed -i -r 's/input_enable_hotkey_btn.*/input_enable_hotkey_btn = "10"/' /tmp/joypads/retrogame_joypad.cfg
fi
